### ISSUE TITLE
Error on HumHub HumDav

### ISSUE THREAD

**Issue by yvangodard** [KeudellCoding/HumHub-Modules-HumDAV#3]
Hi,
I'm trying to use HumDav on HumHub 1.12.1 / PHP 7.4.30 but I'm facing some issues.
I've seen this on my logs 
Error: Class 'DOMDocument' not found in /home/cooperative/www/protected/modules/humdav/vendor/sabre/dav/lib/DAV/Server.php:262
Stack trace:
#0 /home/cooperative/www/protected/modules/humdav/controllers/RemoteController.php(99): Sabre\DAV\Server->exec()
#1 [internal function]: humhub\modules\humdav\controllers\RemoteController->actionIndex()
#2 /home/cooperative/www/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /home/cooperative/www/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#4 /home/cooperative/www/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#5 /home/cooperative/www/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#6 /home/cooperative/www/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#7 /home/cooperative/www/index.php(25): yii\base\Application->run()
#8 {main}

Any idea to solve this ?

**Comment by KarlKeu00** [comment]
I don't know exactly what the bug is right away, but I have updated the sabre version for the next release. Hopefully that should fix the problem.
